services:
  - type: web
    name: edu-timetable
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: edu-timetable-data
      mountPath: /app
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: online
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: FET_ENGINE_PATH
        value: /app/engine/fet-cl
      - key: OUTPUT_DIR
        value: /app/output
      - key: SSO_SHARED_SECRET
        sync: false
      - key: CENTRAL_SERVER_URL
        sync: false
